version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
